spring:
  application:
    name: blogTest
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/new_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456

  # Spring Boot 3 默认 HikariCP，可显式写清楚
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    connection-timeout: 30000

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


server:
  port: 8080

jwt:
  secret: ${JWT_SECRET} #环境变量里找密钥
  expire: 7200 #密钥签发到失效两个小时

oss_access_key:
  id:${OSS_ACCESS_KEY_ID}
  secret:${OSS_ACCESS_KEY_SECRET}
